// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (venue_id, category_name, color_class, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, venue_id, created_at, updated_at, deleted_at, category_name, color_class, icon
`

type CreateCategoryParams struct {
	VenueID      int32       `json:"venue_id"`
	CategoryName string      `json:"category_name"`
	ColorClass   pgtype.Text `json:"color_class"`
	Icon         pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.VenueID, arg.CategoryName, arg.ColorClass, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
		&i.ColorClass,
		&i.Icon,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories SET deleted_at = now() WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
`

type DeleteCategoryParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.VenueID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, venue_id, created_at, updated_at, deleted_at, category_name, color_class, icon
FROM categories
WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
`

type GetCategoryParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.VenueID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
		&i.ColorClass,
		&i.Icon,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, venue_id, created_at, updated_at, deleted_at, category_name, color_class, icon
FROM categories
WHERE venue_id = $1 AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListCategoriesParams struct {
	VenueID int32 `json:"venue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.VenueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.ColorClass,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
  category_name = $3,
  color_class   = $4,
  icon          = $5,
  updated_at    = now()
WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
RETURNING id, venue_id, created_at, updated_at, deleted_at, category_name, color_class, icon
`

type UpdateCategoryParams struct {
	ID           int64       `json:"id"`
	VenueID      int32       `json:"venue_id"`
	CategoryName string      `json:"category_name"`
	ColorClass   pgtype.Text `json:"color_class"`
	Icon         pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.VenueID, arg.CategoryName, arg.ColorClass, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
		&i.ColorClass,
		&i.Icon,
	)
	return i, err
}
