// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
insert into categories (
  venue_id, category_name, is_active
) values ($1, $2, true)
returning id, venue_id, created_at, updated_at, deleted_at, category_name
`

type CreateCategoryParams struct {
	VenueID      int32  `json:"venue_id"`
	CategoryName string `json:"category_name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.VenueID, arg.CategoryName)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
update categories
set deleted_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
`

type DeleteCategoryParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.VenueID)
	return err
}

const getCategory = `-- name: GetCategory :one
select id, venue_id, created_at, updated_at, deleted_at, category_name
from categories
where id = $1 and venue_id = $2 and deleted_at is null
`

type GetCategoryParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.VenueID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
select id, venue_id, created_at, updated_at, deleted_at, category_name
from categories
where venue_id = $1 and deleted_at is null
order by id
limit $2 offset $3
`

type ListCategoriesParams struct {
	VenueID int32 `json:"venue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.VenueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
update categories
set
  category_name = $3,
  updated_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
returning id, venue_id, created_at, updated_at, deleted_at, category_name
`

type UpdateCategoryParams struct {
	ID           int64  `json:"id"`
	VenueID      int32  `json:"venue_id"`
	CategoryName string `json:"category_name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.VenueID, arg.CategoryName)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}
