// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package sqlc

import (
	"context"
)

const createIngredient = `-- name: CreateIngredient :one
insert into ingredients (
  venue_id,
  ingredient_name,
  unit_of_measure,
  ingredient_type
)
values ($1, $2, $3, $4)
returning id, venue_id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
`

type CreateIngredientParams struct {
	VenueID        int32  `json:"venue_id"`
	IngredientName string `json:"ingredient_name"`
	UnitOfMeasure  string `json:"unit_of_measure"`
	IngredientType string `json:"ingredient_type"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.VenueID,
		arg.IngredientName,
		arg.UnitOfMeasure,
		arg.IngredientType,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
update ingredients
set deleted_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
`

type DeleteIngredientParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteIngredient(ctx context.Context, arg DeleteIngredientParams) error {
	_, err := q.db.Exec(ctx, deleteIngredient, arg.ID, arg.VenueID)
	return err
}

const getIngredientByID = `-- name: GetIngredientByID :one
select id, venue_id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
from ingredients
where id = $1 and venue_id = $2 and deleted_at is null
`

type GetIngredientByIDParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetIngredientByID(ctx context.Context, arg GetIngredientByIDParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, arg.ID, arg.VenueID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}

const listAllIngredients = `-- name: ListAllIngredients :many
select id, venue_id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
from ingredients
where venue_id = $1 and deleted_at is null
order by ingredient_name
`

func (q *Queries) ListAllIngredients(ctx context.Context, venueID int32) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listAllIngredients, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IngredientName,
			&i.UnitOfMeasure,
			&i.IngredientType,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
select id, venue_id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
from ingredients
where venue_id = $1 and deleted_at is null
order by id
limit $2 offset $3
`

type ListIngredientsParams struct {
	VenueID int32 `json:"venue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients, arg.VenueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IngredientName,
			&i.UnitOfMeasure,
			&i.IngredientType,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
update ingredients
set
  ingredient_name = $3,
  unit_of_measure = $4,
  ingredient_type = $5,
  stock = $6,
  updated_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
returning id, venue_id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
`

type UpdateIngredientParams struct {
	ID             int64  `json:"id"`
	VenueID        int32  `json:"venue_id"`
	IngredientName string `json:"ingredient_name"`
	UnitOfMeasure  string `json:"unit_of_measure"`
	IngredientType string `json:"ingredient_type"`
	Stock          int64  `json:"stock"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.VenueID,
		arg.IngredientName,
		arg.UnitOfMeasure,
		arg.IngredientType,
		arg.Stock,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}
