// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package sqlc

import (
	"context"
)

const createIngredient = `-- name: CreateIngredient :one
insert into ingredients (
  ingredient_name,
  unit_of_measure,
  ingredient_type
)
values ($1, $2, $3)
returning id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
`

type CreateIngredientParams struct {
	IngredientName string `json:"ingredient_name"`
	UnitOfMeasure  string `json:"unit_of_measure"`
	IngredientType string `json:"ingredient_type"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, arg.IngredientName, arg.UnitOfMeasure, arg.IngredientType)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
update ingredients
set deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIngredient, id)
	return err
}

const getIngredientByID = `-- name: GetIngredientByID :one
select id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
from ingredients
where id = $1 and deleted_at is null
`

func (q *Queries) GetIngredientByID(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientByID, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
select id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
from ingredients
where deleted_at is null
order by id
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IngredientName,
			&i.UnitOfMeasure,
			&i.IngredientType,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
update ingredients
set
  ingredient_name = $2,
  unit_of_measure = $3,
  ingredient_type = $4,
  updated_at = now()
where id = $1 and deleted_at is null
returning id, created_at, updated_at, deleted_at, ingredient_name, unit_of_measure, ingredient_type, stock
`

type UpdateIngredientParams struct {
	ID             int64  `json:"id"`
	IngredientName string `json:"ingredient_name"`
	UnitOfMeasure  string `json:"unit_of_measure"`
	IngredientType string `json:"ingredient_type"`
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.IngredientName,
		arg.UnitOfMeasure,
		arg.IngredientType,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IngredientName,
		&i.UnitOfMeasure,
		&i.IngredientType,
		&i.Stock,
	)
	return i, err
}
