// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID           int64              `json:"id"`
	VenueID      int32              `json:"venue_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CategoryName string             `json:"category_name"`
	ColorClass   pgtype.Text        `json:"color_class"`
	Icon         pgtype.Text        `json:"icon"`
}


type Order struct {
	ID            int64              `json:"id"`
	VenueID       int32              `json:"venue_id"`
	TableID       pgtype.Int8        `json:"table_id"`
	UserID        int32              `json:"user_id"`
	PosTerminalID pgtype.Int4        `json:"pos_terminal_id"`
	StatusID      int32              `json:"status_id"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type OrderItem struct {
	ID        int64              `json:"id"`
	OrderID   int64              `json:"order_id"`
	ProductID int64              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice pgtype.Numeric     `json:"unit_price"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrderStatus struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Owner struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            int64              `json:"id"`
	OrderID       int64              `json:"order_id"`
	DivisionID    pgtype.Text        `json:"division_id"`
	PaymentMethod string             `json:"payment_method"`
	Amount        pgtype.Numeric     `json:"amount"`
	Tip           pgtype.Numeric     `json:"tip"`
	Total         pgtype.Numeric     `json:"total"`
	Status        string             `json:"status"`
	Reference     pgtype.Text        `json:"reference"`
	VenueID       int32              `json:"venue_id"`
	PosTerminalID pgtype.Int4        `json:"pos_terminal_id"`
	UserID        int32              `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PosTerminal struct {
	ID           int32              `json:"id"`
	VenueID      int32              `json:"venue_id"`
	TerminalName string             `json:"terminal_name"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          int64              `json:"id"`
	VenueID     int32              `json:"venue_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProductName string             `json:"product_name"`
	SalesPrice  pgtype.Numeric     `json:"sales_price"`
	IsActive    bool               `json:"is_active"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CategoryID  pgtype.Int8        `json:"category_id"`
}

type ProductCategory struct {
	ID         int64              `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ProductID  int64              `json:"product_id"`
	CategoryID int64              `json:"category_id"`
}


type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Session struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo   pgtype.Text        `json:"device_info"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	IsRevoked    pgtype.Bool        `json:"is_revoked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Table struct {
	IDTable     int64              `json:"id_table"`
	VenueID     int32              `json:"venue_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	TableNumber int32              `json:"table_number"`
	Capacity    int32              `json:"capacity"`
	Status      string             `json:"status"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
}

type User struct {
	ID           int32              `json:"id"`
	VenueID      int32              `json:"venue_id"`
	RoleID       int32              `json:"role_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	PinHash      pgtype.Text        `json:"pin_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Phone        pgtype.Text        `json:"phone"`
	LastAccess   pgtype.Timestamptz `json:"last_access"`
}

type Venue struct {
	ID        int32              `json:"id"`
	OwnerID   int32              `json:"owner_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
