// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CategoryName string             `json:"category_name"`
}

type Ingredient struct {
	ID             int64              `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	IngredientName string             `json:"ingredient_name"`
	UnitOfMeasure  string             `json:"unit_of_measure"`
	IngredientType string             `json:"ingredient_type"`
	Stock          int64              `json:"stock"`
}

type Product struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProductName string             `json:"product_name"`
	SalesPrice  pgtype.Numeric     `json:"sales_price"`
	IsActive    bool               `json:"is_active"`
}

type ProductCategory struct {
	ID         int64              `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ProductID  int64              `json:"product_id"`
	CategoryID int64              `json:"category_id"`
}

type Recipe struct {
	ID               int64              `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProductID        int64              `json:"product_id"`
	IngredientID     int64              `json:"ingredient_id"`
	QuantityRequired pgtype.Numeric     `json:"quantity_required"`
}

type User struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
}

type Waitress struct {
	IDUser int64 `json:"id_user"`
}
