// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CategoryName string             `json:"category_name"`
}

type Ingredient struct {
	ID             int64              `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	IngredientName string             `json:"ingredient_name"`
	UnitOfMeasure  string             `json:"unit_of_measure"`
	IngredientType string             `json:"ingredient_type"`
	Stock          int64              `json:"stock"`
}

type Product struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProductName string             `json:"product_name"`
	SalesPrice  pgtype.Numeric     `json:"sales_price"`
	IsActive    bool               `json:"is_active"`
}

type ProductCategory struct {
	ID         int64              `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ProductID  int64              `json:"product_id"`
	CategoryID int64              `json:"category_id"`
}

type Recipe struct {
	ID               int64              `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProductID        int64              `json:"product_id"`
	IngredientID     int64              `json:"ingredient_id"`
	QuantityRequired pgtype.Numeric     `json:"quantity_required"`
}

type Restaurant struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Session struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo   pgtype.Text        `json:"device_info"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	IsRevoked    pgtype.Bool        `json:"is_revoked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	RestaurantID int32              `json:"restaurant_id"`
	RoleID       int32              `json:"role_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
