// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pos_terminals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTerminal = `-- name: CreateTerminal :one
INSERT INTO pos_terminals (
  venue_id, terminal_name
) VALUES (
  $1, $2
)
RETURNING id, venue_id, terminal_name, is_active, created_at, updated_at
`

type CreateTerminalParams struct {
	VenueID      int32  `json:"venue_id"`
	TerminalName string `json:"terminal_name"`
}

func (q *Queries) CreateTerminal(ctx context.Context, arg CreateTerminalParams) (PosTerminal, error) {
	row := q.db.QueryRow(ctx, createTerminal, arg.VenueID, arg.TerminalName)
	var i PosTerminal
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.TerminalName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTerminalByID = `-- name: GetTerminalByID :one
SELECT id, venue_id, terminal_name, is_active, created_at, updated_at FROM pos_terminals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTerminalByID(ctx context.Context, id int32) (PosTerminal, error) {
	row := q.db.QueryRow(ctx, getTerminalByID, id)
	var i PosTerminal
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.TerminalName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTerminalsByVenue = `-- name: ListTerminalsByVenue :many
SELECT id, venue_id, terminal_name, is_active, created_at, updated_at FROM pos_terminals
WHERE venue_id = $1 AND is_active = true
ORDER BY terminal_name
`

func (q *Queries) ListTerminalsByVenue(ctx context.Context, venueID int32) ([]PosTerminal, error) {
	rows, err := q.db.Query(ctx, listTerminalsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PosTerminal{}
	for rows.Next() {
		var i PosTerminal
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.TerminalName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTerminal = `-- name: UpdateTerminal :one
UPDATE pos_terminals
SET terminal_name = $2,
    is_active = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, venue_id, terminal_name, is_active, created_at, updated_at
`

type UpdateTerminalParams struct {
	ID           int32       `json:"id"`
	TerminalName string      `json:"terminal_name"`
	IsActive     pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateTerminal(ctx context.Context, arg UpdateTerminalParams) (PosTerminal, error) {
	row := q.db.QueryRow(ctx, updateTerminal, arg.ID, arg.TerminalName, arg.IsActive)
	var i PosTerminal
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.TerminalName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
