// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
insert into products (
  product_name,
  sales_price,
  is_active
) values ($1, $2, $3)
returning id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
`

type CreateProductParams struct {
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.ProductName, arg.SalesPrice, arg.IsActive)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
update products
set deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
select id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
from products
where id = $1 and deleted_at is null
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
select id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
from products
where deleted_at is null
order by id
limit $1 offset $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.SalesPrice,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
update products
set
  product_name = $2,
  sales_price = $3,
  is_active = $4,
  updated_at = now()
where id = $1 and deleted_at is null
returning id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
`

type UpdateProductParams struct {
	ID          int64          `json:"id"`
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.ProductName,
		arg.SalesPrice,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}
