// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
insert into products (
  venue_id,
  product_name,
  sales_price,
  is_active
) values ($1, $2, $3, $4)
returning id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
`

type CreateProductParams struct {
	VenueID     int32          `json:"venue_id"`
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.VenueID,
		arg.ProductName,
		arg.SalesPrice,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
update products
set deleted_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
`

type DeleteProductParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.VenueID)
	return err
}

const getProduct = `-- name: GetProduct :one
select id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
from products
where id = $1 and venue_id = $2 and deleted_at is null
`

type GetProductParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.VenueID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
select id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
from products
where venue_id = $1 and deleted_at is null
order by id
limit $2 offset $3
`

type ListProductsParams struct {
	VenueID int32 `json:"venue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.VenueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.SalesPrice,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
update products
set
  product_name = $3,
  sales_price = $4,
  is_active = $5,
  updated_at = now()
where id = $1 and venue_id = $2 and deleted_at is null
returning id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active
`

type UpdateProductParams struct {
	ID          int64          `json:"id"`
	VenueID     int32          `json:"venue_id"`
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.VenueID,
		arg.ProductName,
		arg.SalesPrice,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
	)
	return i, err
}
