// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  venue_id, product_name, sales_price, is_active, description, image_url, category_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active, description, image_url, category_id
`

type CreateProductParams struct {
	VenueID     int32          `json:"venue_id"`
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
	Description pgtype.Text    `json:"description"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	CategoryID  pgtype.Int8    `json:"category_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.VenueID,
		arg.ProductName,
		arg.SalesPrice,
		arg.IsActive,
		arg.Description,
		arg.ImageUrl,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
		&i.Description,
		&i.ImageUrl,
		&i.CategoryID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products SET deleted_at = now() WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
`

type DeleteProductParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.VenueID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active, description, image_url, category_id
FROM products
WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
`

type GetProductParams struct {
	ID      int64 `json:"id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.VenueID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
		&i.Description,
		&i.ImageUrl,
		&i.CategoryID,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active, description, image_url, category_id
FROM products
WHERE venue_id = $1 AND deleted_at IS NULL
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	VenueID int32 `json:"venue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.VenueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.SalesPrice,
			&i.IsActive,
			&i.Description,
			&i.ImageUrl,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  product_name = $3,
  sales_price  = $4,
  is_active    = $5,
  description  = $6,
  image_url    = $7,
  category_id  = $8,
  updated_at   = now()
WHERE id = $1 AND venue_id = $2 AND deleted_at IS NULL
RETURNING id, venue_id, created_at, updated_at, deleted_at, product_name, sales_price, is_active, description, image_url, category_id
`

type UpdateProductParams struct {
	ID          int64          `json:"id"`
	VenueID     int32          `json:"venue_id"`
	ProductName string         `json:"product_name"`
	SalesPrice  pgtype.Numeric `json:"sales_price"`
	IsActive    bool           `json:"is_active"`
	Description pgtype.Text    `json:"description"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	CategoryID  pgtype.Int8    `json:"category_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.VenueID,
		arg.ProductName,
		arg.SalesPrice,
		arg.IsActive,
		arg.Description,
		arg.ImageUrl,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.SalesPrice,
		&i.IsActive,
		&i.Description,
		&i.ImageUrl,
		&i.CategoryID,
	)
	return i, err
}
