// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateTerminal(ctx context.Context, arg CreateTerminalParams) (PosTerminal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteTable(ctx context.Context, arg DeleteTableParams) error
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetOwnerByEmail(ctx context.Context, email string) (Owner, error)
	GetOwnerByID(ctx context.Context, id int32) (Owner, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetRoleByID(ctx context.Context, id int32) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (Session, error)
	GetTable(ctx context.Context, arg GetTableParams) (Table, error)
	GetTerminalByID(ctx context.Context, id int32) (PosTerminal, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetVenueByID(ctx context.Context, id int32) (Venue, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListOwners(ctx context.Context) ([]Owner, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListTables(ctx context.Context, venueID int32) ([]Table, error)
	ListTerminalsByVenue(ctx context.Context, venueID int32) ([]PosTerminal, error)
	ListUsersByVenue(ctx context.Context, venueID int32) ([]User, error)
	ListVenuesByOwner(ctx context.Context, ownerID int32) ([]Venue, error)
	RevokeSession(ctx context.Context, refreshToken string) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateOwner(ctx context.Context, arg UpdateOwnerParams) (Owner, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateTable(ctx context.Context, arg UpdateTableParams) error
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (Table, error)
	UpdateTerminal(ctx context.Context, arg UpdateTerminalParams) (PosTerminal, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastAccess(ctx context.Context, id int32) error
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error)
}

var _ Querier = (*Queries)(nil)
