// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipeItem = `-- name: AddRecipeItem :one
insert into recipe (
  product_id,
  ingredient_id,
  quantity_required
) values ($1, $2, $3)
returning id, created_at, updated_at, deleted_at, product_id, ingredient_id, quantity_required
`

type AddRecipeItemParams struct {
	ProductID        int64          `json:"product_id"`
	IngredientID     int64          `json:"ingredient_id"`
	QuantityRequired pgtype.Numeric `json:"quantity_required"`
}

func (q *Queries) AddRecipeItem(ctx context.Context, arg AddRecipeItemParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, addRecipeItem, arg.ProductID, arg.IngredientID, arg.QuantityRequired)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductID,
		&i.IngredientID,
		&i.QuantityRequired,
	)
	return i, err
}

const deleteRecipeItem = `-- name: DeleteRecipeItem :exec
update recipe
set deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) DeleteRecipeItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeItem, id)
	return err
}

const getRecipeByProductID = `-- name: GetRecipeByProductID :many
select r.id, r.product_id, r.ingredient_id, r.quantity_required, i.ingredient_name, i.unit_of_measure
from recipe r
join ingredients i on r.ingredient_id = i.id
where r.product_id = $1 and r.deleted_at is null
`

type GetRecipeByProductIDRow struct {
	ID               int64          `json:"id"`
	ProductID        int64          `json:"product_id"`
	IngredientID     int64          `json:"ingredient_id"`
	QuantityRequired pgtype.Numeric `json:"quantity_required"`
	IngredientName   string         `json:"ingredient_name"`
	UnitOfMeasure    string         `json:"unit_of_measure"`
}

func (q *Queries) GetRecipeByProductID(ctx context.Context, productID int64) ([]GetRecipeByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getRecipeByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecipeByProductIDRow{}
	for rows.Next() {
		var i GetRecipeByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.IngredientID,
			&i.QuantityRequired,
			&i.IngredientName,
			&i.UnitOfMeasure,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
