// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
insert into sales (
  total,
  payment_method,
  date,
  order_id
)
values ($1, $2, $3, $4)
returning id, total, payment_method, date, order_id, created_at, updated_at, deleted_at
`

type CreateSaleParams struct {
	Total         pgtype.Numeric     `json:"total"`
	PaymentMethod string             `json:"payment_method"`
	Date          pgtype.Timestamptz `json:"date"`
	OrderID       int32              `json:"order_id"`
}

type CreateSaleRow struct {
	ID            int64              `json:"id"`
	Total         pgtype.Numeric     `json:"total"`
	PaymentMethod string             `json:"payment_method"`
	Date          pgtype.Timestamptz `json:"date"`
	OrderID       int32              `json:"order_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (CreateSaleRow, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.Total,
		arg.PaymentMethod,
		arg.Date,
		arg.OrderID,
	)
	var i CreateSaleRow
	err := row.Scan(
		&i.ID,
		&i.Total,
		&i.PaymentMethod,
		&i.Date,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
select id, total, payment_method, date, order_id, created_at, updated_at, deleted_at
from sales
where id = $1 and deleted_at is null
`

type GetSaleByIDRow struct {
	ID            int64              `json:"id"`
	Total         pgtype.Numeric     `json:"total"`
	PaymentMethod string             `json:"payment_method"`
	Date          pgtype.Timestamptz `json:"date"`
	OrderID       int32              `json:"order_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetSaleByID(ctx context.Context, id int64) (GetSaleByIDRow, error) {
	row := q.db.QueryRow(ctx, getSaleByID, id)
	var i GetSaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Total,
		&i.PaymentMethod,
		&i.Date,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
