// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
  venue_id, table_number, status, capacity, arrival_time
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id_table, venue_id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time
`

type CreateTableParams struct {
	VenueID     int32              `json:"venue_id"`
	TableNumber int32              `json:"table_number"`
	Status      string             `json:"status"`
	Capacity    int32              `json:"capacity"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.VenueID,
		arg.TableNumber,
		arg.Status,
		arg.Capacity,
		arg.ArrivalTime,
	)
	var i Table
	err := row.Scan(
		&i.IDTable,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables
WHERE id_table = $1 AND venue_id = $2
`

type DeleteTableParams struct {
	IDTable int64 `json:"id_table"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) DeleteTable(ctx context.Context, arg DeleteTableParams) error {
	_, err := q.db.Exec(ctx, deleteTable, arg.IDTable, arg.VenueID)
	return err
}

const getTable = `-- name: GetTable :one
SELECT id_table, venue_id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time FROM tables
WHERE id_table = $1 AND venue_id = $2 LIMIT 1
`

type GetTableParams struct {
	IDTable int64 `json:"id_table"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetTable(ctx context.Context, arg GetTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, getTable, arg.IDTable, arg.VenueID)
	var i Table
	err := row.Scan(
		&i.IDTable,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT id_table, venue_id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time FROM tables
WHERE venue_id = $1
ORDER BY table_number
`

func (q *Queries) ListTables(ctx context.Context, venueID int32) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTables, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.IDTable,
			&i.VenueID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.ArrivalTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTable = `-- name: UpdateTable :exec
UPDATE tables
SET 
    table_number = COALESCE($1, table_number),
    capacity     = COALESCE($2, capacity),
    status       = COALESCE($3, status),
    arrival_time = COALESCE($4, arrival_time),
    updated_at   = now()
WHERE id_table = $5 AND venue_id = $6
`

type UpdateTableParams struct {
	TableNumber pgtype.Int4        `json:"table_number"`
	Capacity    pgtype.Int4        `json:"capacity"`
	Status      pgtype.Text        `json:"status"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
	IDTable     int64              `json:"id_table"`
	VenueID     int32              `json:"venue_id"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) error {
	_, err := q.db.Exec(ctx, updateTable,
		arg.TableNumber,
		arg.Capacity,
		arg.Status,
		arg.ArrivalTime,
		arg.IDTable,
		arg.VenueID,
	)
	return err
}

const updateTableStatus = `-- name: UpdateTableStatus :one
UPDATE tables
SET status = $3, arrival_time = $4, updated_at = now()
WHERE id_table = $1 AND venue_id = $2
RETURNING id_table, venue_id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time
`

type UpdateTableStatusParams struct {
	IDTable     int64              `json:"id_table"`
	VenueID     int32              `json:"venue_id"`
	Status      string             `json:"status"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (Table, error) {
	row := q.db.QueryRow(ctx, updateTableStatus,
		arg.IDTable,
		arg.VenueID,
		arg.Status,
		arg.ArrivalTime,
	)
	var i Table
	err := row.Scan(
		&i.IDTable,
		&i.VenueID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}
