// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_assignments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignWaiterToTable = `-- name: AssignWaiterToTable :one
INSERT INTO table_assignments (table_id, user_id, venue_id)
VALUES ($1, $2, $3)
RETURNING id, table_id, user_id, venue_id, assigned_at, unassigned_at
`

type AssignWaiterToTableParams struct {
	TableID int64 `json:"table_id"`
	UserID  int32 `json:"user_id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) AssignWaiterToTable(ctx context.Context, arg AssignWaiterToTableParams) (TableAssignment, error) {
	row := q.db.QueryRow(ctx, assignWaiterToTable, arg.TableID, arg.UserID, arg.VenueID)
	var i TableAssignment
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.UserID,
		&i.VenueID,
		&i.AssignedAt,
		&i.UnassignedAt,
	)
	return i, err
}

const getActiveAssignment = `-- name: GetActiveAssignment :one
SELECT id, table_id, user_id, venue_id, assigned_at, unassigned_at FROM table_assignments
WHERE table_id = $1 AND venue_id = $2 AND unassigned_at IS NULL
LIMIT 1
`

type GetActiveAssignmentParams struct {
	TableID int64 `json:"table_id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) GetActiveAssignment(ctx context.Context, arg GetActiveAssignmentParams) (TableAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignment, arg.TableID, arg.VenueID)
	var i TableAssignment
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.UserID,
		&i.VenueID,
		&i.AssignedAt,
		&i.UnassignedAt,
	)
	return i, err
}

const listActiveAssignmentsByVenue = `-- name: ListActiveAssignmentsByVenue :many
SELECT ta.id, ta.table_id, ta.user_id, ta.venue_id, ta.assigned_at, ta.unassigned_at, u.name AS waiter_name, t.table_number
FROM table_assignments ta
JOIN users u ON u.id = ta.user_id
JOIN tables t ON t.id_table = ta.table_id
WHERE ta.venue_id = $1 AND ta.unassigned_at IS NULL
ORDER BY t.table_number
`

type ListActiveAssignmentsByVenueRow struct {
	ID           int64              `json:"id"`
	TableID      int64              `json:"table_id"`
	UserID       int32              `json:"user_id"`
	VenueID      int32              `json:"venue_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
	WaiterName   string             `json:"waiter_name"`
	TableNumber  int32              `json:"table_number"`
}

func (q *Queries) ListActiveAssignmentsByVenue(ctx context.Context, venueID int32) ([]ListActiveAssignmentsByVenueRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsByVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAssignmentsByVenueRow{}
	for rows.Next() {
		var i ListActiveAssignmentsByVenueRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.UserID,
			&i.VenueID,
			&i.AssignedAt,
			&i.UnassignedAt,
			&i.WaiterName,
			&i.TableNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByTable = `-- name: ListAssignmentsByTable :many
SELECT ta.id, ta.table_id, ta.user_id, ta.venue_id, ta.assigned_at, ta.unassigned_at, u.name AS waiter_name
FROM table_assignments ta
JOIN users u ON u.id = ta.user_id
WHERE ta.table_id = $1 AND ta.venue_id = $2
ORDER BY ta.assigned_at DESC
`

type ListAssignmentsByTableParams struct {
	TableID int64 `json:"table_id"`
	VenueID int32 `json:"venue_id"`
}

type ListAssignmentsByTableRow struct {
	ID           int64              `json:"id"`
	TableID      int64              `json:"table_id"`
	UserID       int32              `json:"user_id"`
	VenueID      int32              `json:"venue_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
	WaiterName   string             `json:"waiter_name"`
}

func (q *Queries) ListAssignmentsByTable(ctx context.Context, arg ListAssignmentsByTableParams) ([]ListAssignmentsByTableRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByTable, arg.TableID, arg.VenueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByTableRow{}
	for rows.Next() {
		var i ListAssignmentsByTableRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.UserID,
			&i.VenueID,
			&i.AssignedAt,
			&i.UnassignedAt,
			&i.WaiterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignWaiterFromTable = `-- name: UnassignWaiterFromTable :exec
UPDATE table_assignments
SET unassigned_at = NOW()
WHERE table_id = $1 AND venue_id = $2 AND unassigned_at IS NULL
`

type UnassignWaiterFromTableParams struct {
	TableID int64 `json:"table_id"`
	VenueID int32 `json:"venue_id"`
}

func (q *Queries) UnassignWaiterFromTable(ctx context.Context, arg UnassignWaiterFromTableParams) error {
	_, err := q.db.Exec(ctx, unassignWaiterFromTable, arg.TableID, arg.VenueID)
	return err
}
