// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignWaitressToTable = `-- name: AssignWaitressToTable :one

INSERT INTO table_waitress (
  table_id, waitress_id
) VALUES (
  $1, $2
) RETURNING id, created_at, updated_at, deleted_at, table_id, waitress_id
`

type AssignWaitressToTableParams struct {
	TableID    int64 `json:"table_id"`
	WaitressID int64 `json:"waitress_id"`
}

// SECCION: Asignación de Mesas (Table Waitress) --
func (q *Queries) AssignWaitressToTable(ctx context.Context, arg AssignWaitressToTableParams) (TableWaitress, error) {
	row := q.db.QueryRow(ctx, assignWaitressToTable, arg.TableID, arg.WaitressID)
	var i TableWaitress
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableID,
		&i.WaitressID,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
  table_number, status, capacity, arrival_time
) VALUES (
  $1, $2, $3, $4
) RETURNING id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time
`

type CreateTableParams struct {
	TableNumber int32              `json:"table_number"`
	Status      string             `json:"status"`
	Capacity    int32              `json:"capacity"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.TableNumber,
		arg.Status,
		arg.Capacity,
		arg.ArrivalTime,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables
WHERE id = $1
`

func (q *Queries) DeleteTable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTable, id)
	return err
}

const getTable = `-- name: GetTable :one
SELECT id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time FROM tables
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTable(ctx context.Context, id int64) (Table, error) {
	row := q.db.QueryRow(ctx, getTable, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}

const getWaitressByTable = `-- name: GetWaitressByTable :one
SELECT id, created_at, updated_at, deleted_at, table_id, waitress_id FROM table_waitress
WHERE table_id = $1 LIMIT 1
`

func (q *Queries) GetWaitressByTable(ctx context.Context, tableID int64) (TableWaitress, error) {
	row := q.db.QueryRow(ctx, getWaitressByTable, tableID)
	var i TableWaitress
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableID,
		&i.WaitressID,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time FROM tables
ORDER BY table_number
`

func (q *Queries) ListTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.ArrivalTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWaitressFromTable = `-- name: RemoveWaitressFromTable :exec
DELETE FROM table_waitress
WHERE table_id = $1
`

func (q *Queries) RemoveWaitressFromTable(ctx context.Context, tableID int64) error {
	_, err := q.db.Exec(ctx, removeWaitressFromTable, tableID)
	return err
}

const updateTable = `-- name: UpdateTable :exec
UPDATE tables
SET 
    -- COALESCE significa: "Si el primer valor es nulo, usa el segundo"
    -- sqlc.narg() permite pasar nulos desde Go
    table_number = COALESCE($1, table_number),
    capacity     = COALESCE($2, capacity),
    status       = COALESCE($3, status),
    arrival_time = COALESCE($4, arrival_time),
    updated_at   = now()
WHERE id = $5
`

type UpdateTableParams struct {
	TableNumber pgtype.Int4        `json:"table_number"`
	Capacity    pgtype.Int4        `json:"capacity"`
	Status      pgtype.Text        `json:"status"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
	ID          int64              `json:"id"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) error {
	_, err := q.db.Exec(ctx, updateTable,
		arg.TableNumber,
		arg.Capacity,
		arg.Status,
		arg.ArrivalTime,
		arg.ID,
	)
	return err
}

const updateTableStatus = `-- name: UpdateTableStatus :one
UPDATE tables
SET status = $2, arrival_time = $3, updated_at = now()
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, table_number, capacity, status, arrival_time
`

type UpdateTableStatusParams struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	ArrivalTime pgtype.Timestamptz `json:"arrival_time"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (Table, error) {
	row := q.db.QueryRow(ctx, updateTableStatus, arg.ID, arg.Status, arg.ArrivalTime)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.ArrivalTime,
	)
	return i, err
}
