// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (
  name, address, phone
) VALUES (
  $1, $2, $3
)
RETURNING id, name, address, phone, is_active, created_at, updated_at
`

type CreateRestaurantParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurant, arg.Name, arg.Address, arg.Phone)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id, refresh_token, expires_at, device_info, ip_address
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, refresh_token, expires_at, device_info, ip_address, is_revoked, created_at
`

type CreateSessionParams struct {
	UserID       int32              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	DeviceInfo   pgtype.Text        `json:"device_info"`
	IpAddress    pgtype.Text        `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.DeviceInfo,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  restaurant_id, role_id, name, email, password_hash
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, restaurant_id, role_id, name, email, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	RestaurantID int32  `json:"restaurant_id"`
	RoleID       int32  `json:"role_id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.RestaurantID,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, name, address, phone, is_active, created_at, updated_at FROM restaurants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id int32) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description FROM roles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description FROM roles
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, refresh_token, expires_at, device_info, ip_address, is_revoked, created_at FROM sessions
WHERE refresh_token = $1 LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, restaurant_id, role_id, name, email, password_hash, is_active, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, restaurant_id, role_id, name, email, password_hash, is_active, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByRestaurant = `-- name: ListUsersByRestaurant :many
SELECT id, restaurant_id, role_id, name, email, password_hash, is_active, created_at, updated_at FROM users
WHERE restaurant_id = $1
ORDER BY name
`

func (q *Queries) ListUsersByRestaurant(ctx context.Context, restaurantID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.RoleID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET is_revoked = true
WHERE refresh_token = $1
`

func (q *Queries) RevokeSession(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, revokeSession, refreshToken)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :one
UPDATE restaurants
SET name = $2,
    address = $3,
    phone = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, address, phone, is_active, created_at, updated_at
`

type UpdateRestaurantParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, updateRestaurant,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.IsActive,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    email = $3,
    is_active = $4,
    role_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, restaurant_id, role_id, name, email, password_hash, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	IsActive pgtype.Bool `json:"is_active"`
	RoleID   int32       `json:"role_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.IsActive,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.RoleID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
