// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
  owner_id, name, address, phone
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, owner_id, name, address, phone, is_active, created_at, updated_at
`

type CreateVenueParams struct {
	OwnerID int32       `json:"owner_id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.OwnerID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, owner_id, name, address, phone, is_active, created_at, updated_at FROM venues
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVenueByID(ctx context.Context, id int32) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenuesByOwner = `-- name: ListVenuesByOwner :many
SELECT id, owner_id, name, address, phone, is_active, created_at, updated_at FROM venues
WHERE owner_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListVenuesByOwner(ctx context.Context, ownerID int32) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET name = $2,
    address = $3,
    phone = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, owner_id, name, address, phone, is_active, created_at, updated_at
`

type UpdateVenueParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.IsActive,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
