// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitress.sql

package sqlc

import (
	"context"
)

const createWaitress = `-- name: CreateWaitress :one
INSERT INTO waitress (
  id_user
) VALUES (
  $1
) RETURNING id_user
`

func (q *Queries) CreateWaitress(ctx context.Context, idUser int64) (int64, error) {
	row := q.db.QueryRow(ctx, createWaitress, idUser)
	var id_user int64
	err := row.Scan(&id_user)
	return id_user, err
}

const deleteWaitress = `-- name: DeleteWaitress :exec
DELETE FROM waitress
WHERE id_user = $1
`

func (q *Queries) DeleteWaitress(ctx context.Context, idUser int64) error {
	_, err := q.db.Exec(ctx, deleteWaitress, idUser)
	return err
}

const getWaitress = `-- name: GetWaitress :one
SELECT id_user FROM waitress
WHERE id_user = $1 LIMIT 1
`

func (q *Queries) GetWaitress(ctx context.Context, idUser int64) (int64, error) {
	row := q.db.QueryRow(ctx, getWaitress, idUser)
	var id_user int64
	err := row.Scan(&id_user)
	return id_user, err
}

const listWaitresses = `-- name: ListWaitresses :many
SELECT id_user FROM waitress
ORDER BY id_user
`

func (q *Queries) ListWaitresses(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listWaitresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id_user int64
		if err := rows.Scan(&id_user); err != nil {
			return nil, err
		}
		items = append(items, id_user)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
